### ISSUE TITLE
Demo 2: Raw speech 

### ISSUE THREAD

**Issue by pbaljeka** [monikaUPF/PraatontheWeb#1]
Why are points belonging to the prosodic phrase break  18 being annotated as pph 15 in the prominence tier? Moreover, shouldn't there be at least one word labelled as prominent in each prosodic break? But the example with raw speech is missing pph 16-18.

**Comment by monikaUPF** [comment]
In the raw speech configuration, numbers of prominent points refer to the voice fragment detected by module 1. As prosodic phrases do not use any phonological nor linguistic information, it was agreed not to rely fully on their prediction to avoid dragging errors to the prominence detection module. Do not hesitate to email me for further details or support on a specific task (monica.dominguez@upf.edu).

**Comment by pbaljeka** [comment]
what does dur_all and dur_pph  feature of x% and y% mean?
